# Gated check-in (GC) build - which build and test

trigger:
  branches:
    exclude:
    - master

pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - azure-pipelines.yml

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  feedName: 'AspNetCoreIdentityFramework'
  azureDevOpsProjectName: 'AspNetCoreIdentityFramework'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore packages
  inputs:
    command: restore
    projects: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: 'Build AspNetCoreIdentityFramework Solution'
  inputs:
    configuration: $(buildConfiguration)
    command: 'build'
    projects: AspNetCoreIdentityFramework.sln

- task: VSTest@2
  displayName: 'Run all Tests'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\Globe.*.Tests.dll
      !**\Globe.Identity.MultiTenant.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'

- task: DotNetCoreCLI@2
  displayName: 'Pack Globe.Identity'
  inputs:
    command: 'pack'
    arguments: --output $(build.artifactstagingdirectory) --configuration $(buildConfiguration)
    packagesToPack: 'Globe.Identity/Globe.Identity.csproj'
    versioningScheme: byPrereleaseNumber
    versionEnvVar: byPrereleaseNumber
    majorVersion: 0
    minorVersion: 1
    patchVersion: 0

- task: DotNetCoreCLI@2
  displayName: 'Pack Globe.Infrastructure.EFCore'
  inputs:
    command: 'pack'
    arguments: --output $(build.artifactstagingdirectory) --configuration $(buildConfiguration)
    packagesToPack: 'Globe.Infrastructure.EFCore/Globe.Infrastructure.EFCore.csproj'
    versioningScheme: byPrereleaseNumber
    versionEnvVar: byPrereleaseNumber
    majorVersion: 0
    minorVersion: 1
    patchVersion: 0

- task: DotNetCoreCLI@2
  displayName: 'Pack Globe.BusinessLogic'
  inputs:
    command: 'pack'
    arguments: --output $(build.artifactstagingdirectory) --configuration $(buildConfiguration)
    packagesToPack: 'Globe.BusinessLogic/Globe.BusinessLogic.csproj'
    versioningScheme: byPrereleaseNumber
    versionEnvVar: byPrereleaseNumber
    majorVersion: 0
    minorVersion: 1
    patchVersion: 0

- task: DotNetCoreCLI@2
  displayName: 'Push artifacts in $(azureDevOpsProjectName)/$(feedName) feed'
  inputs:
    command: 'push'
    nuGetFeedType: 'internal'
    packagesToPush: '$(build.artifactStagingDirectory)/*.nupkg'
    publishVstsFeed: '$(azureDevOpsProjectName)/$(feedName)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'