# Standard CI build - which build, test and publish artifact

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - azure-pipelines-gc.yml

pr: none

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  feedName: 'AspNetCoreIdentityFramework'
  azureDevOpsProjectName: 'AspNetCoreIdentityFramework'
  GitVersion.SemVer: ''

steps:
# Update AssemblyInfo Files
- task: UseGitVersion@5
  displayName: 'Git Version updates SharedAssemblyInfo'
  inputs:
    versionSpec: '5.x'
    configFilePath: 'gitversion.yml'
    updateAssemblyInfo: true
    updateAssemblyInfoFilename: '$(system.defaultworkingdirectory)\SharedAssemblyInfo.cs'

# Build Solution
- task: DotNetCoreCLI@2
  displayName: Restore packages
  inputs:
    command: restore
    projects: '**/*.sln'
- task: DotNetCoreCLI@2
  displayName: 'Build AspNetCoreIdentityFramework Solution'
  inputs:
    arguments: '-p:Version=$(GitVersion.AssemblySemVer) --configuration $(buildConfiguration)'
    command: 'build'
    projects: AspNetCoreIdentityFramework.sln
    versioningScheme: byEnvVar
    versionEnvVar: 'GitVersion.SemVer'

# Test Projects
- task: VSTest@2
  displayName: 'Run all Tests'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\Globe.*.Tests.dll
      !**\Globe.Identity.MultiTenant.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'

# Publish Artifacts
- task: DotNetCoreCLI@2
  displayName: 'Pack Globe.Identity'
  inputs:
    command: 'pack'
    arguments: --output $(build.artifactstagingdirectory) --configuration $(buildConfiguration)
    packagesToPack: 'Globe.Identity/Globe.Identity.csproj'
- task: DotNetCoreCLI@2
  displayName: 'Pack Globe.Infrastructure.EFCore'
  inputs:
    command: 'pack'
    arguments: --output $(build.artifactstagingdirectory) --configuration $(buildConfiguration)
    packagesToPack: 'Globe.Infrastructure.EFCore/Globe.Infrastructure.EFCore.csproj'
- task: DotNetCoreCLI@2
  displayName: 'Pack Globe.BusinessLogic'
  inputs:
    command: 'pack'
    arguments: --output $(build.artifactstagingdirectory) --configuration $(buildConfiguration)
    packagesToPack: 'Globe.BusinessLogic/Globe.BusinessLogic.csproj'
- task: DotNetCoreCLI@2
  displayName: 'Pack Globe.Tests'
  inputs:
    command: 'pack'
    arguments: --output $(build.artifactstagingdirectory) --configuration $(buildConfiguration)
    packagesToPack: 'Globe.Tests/Globe.Tests.csproj'
- task: DotNetCoreCLI@2
  displayName: 'Push artifacts in $(azureDevOpsProjectName)/$(feedName) feed'
  inputs:
    command: 'push'
    nuGetFeedType: 'internal'
    packagesToPush: '$(build.artifactStagingDirectory)/*.nupkg'
    publishVstsFeed: '$(azureDevOpsProjectName)/$(feedName)'