# .NET Core
# Build and test .NET Core projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  folderName: 'Globe.Identity'
  projectName: 'Globe.Identity'
  feedName: 'Globe-UltraLocalizer'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build $(projectName)'
  inputs:
    command: 'pack'
    arguments: --output $(build.artifactstagingdirectory) --configuration $(buildConfiguration)
    packagesToPack: '$(folderName)/$(projectName).csproj'
    versioningScheme: byPrereleaseNumber
    versionEnvVar: byPrereleaseNumber
    majorVersion: 0
    minorVersion: 1
    patchVersion: 0

- task: DotNetCoreCLI@2
  displayName: 'Put $(projectName).dll in $(feedName) feed'
  inputs:
    command: 'push'
    nuGetFeedType: 'internal'
    packagesToPush: '$(build.artifactStagingDirectory)/*.nupkg'
    publishVstsFeed: '$(projectName)/$(feedName)'

- task: PublishBuildArtifacts@1