version: '3.7'

services:
 globe-translation-server:
  build:
   context: ./
   dockerfile: globe.translationserver.Dockerfile
  restart: always
  ports:
   - "7000:80"
   - "7005:443"
  environment:
   ASPNETCORE_ENVIRONMENT: Docker
   ASPNETCORE_URLS: https://+;http://+
   ASPNETCORE_HTTPS_PORT: 7005
   ASPNETCORE_Kestrel__Certificates__Default__Path: /https/globe.translationserver.pfx
   ASPNETCORE_Kestrel__Certificates__Default__Password: globe
   ASPNETCORE_JwtAuthenticationOptions__ComeFrom: docker
   ASPNETCORE_JwtAuthenticationOptions__SecretKey: iNivDmHLpUA223sqsfhqGbMRdRj1PVkH
   ASPNETCORE_JwtAuthenticationOptions__Issuer: www.identityserver.com
   ASPNETCORE_JwtAuthenticationOptions__Audience: www.translationserver.com
  volumes:
   - /https:/https:rw