version: '3.7'

services:
 globe-translation-server:
  build:
   context: ./
   dockerfile: globe.translationserver.Dockerfile
  restart: always
  ports:
   - "7000:80"
   - "7005:443"
  environment:
   ASPNETCORE_ENVIRONMENT: Docker
   ASPNETCORE_URLS: https://+;http://+
   ASPNETCORE_HTTPS_PORT: 7005
   ASPNETCORE_Kestrel__Certificates__Default__Path: /https/globe.translationserver.pfx
   ASPNETCORE_Kestrel__Certificates__Default__Password: globe
   ASPNETCORE_JwtAuthenticationOptions__ComeFrom: docker
   ASPNETCORE_JwtAuthenticationOptions__SecretKey: iNivDmHLpUA223sqsfhqGbMRdRj1PVkH
   ASPNETCORE_JwtAuthenticationOptions__Issuer: www.identityserver.com
   ASPNETCORE_JwtAuthenticationOptions__Audience: www.translationserver.com
  volumes:
   - /https:/https:rw

 globe-identity-server:
  build:
   context: ./
   dockerfile: globe.identityserver.Dockerfile
  restart: always
  ports:
   - "8000:80"
   - "8005:443"
  environment:
   ASPNETCORE_ENVIRONMENT: Docker
   ASPNETCORE_URLS: https://+;http://+
   ASPNETCORE_HTTPS_PORT: 8005
   ASPNETCORE_Kestrel__Certificates__Default__Path: /https/globe.translationserver.pfx
   ASPNETCORE_Kestrel__Certificates__Default__Password: globe
   ASPNETCORE_JwtAuthenticationOptions__ComeFrom: docker
   ASPNETCORE_JwtAuthenticationOptions__SecretKey: iNivDmHLpUA223sqsfhqGbMRdRj1PVkH
   ASPNETCORE_JwtAuthenticationOptions__Issuer: www.identityserver.com
   ASPNETCORE_JwtAuthenticationOptions__Audience: www.translationserver.com
   ASPNETCORE_ConnectionStrings__DefaultSqlServerConnection: "Server=192.168.99.100,1433;Database=IdentityAdministrativeDashboard;User=sa;Password=MyPassword001;"
   #connection string for database running on local machine
   #ASPNETCORE_ConnectionStrings__DefaultSqlServerConnection: "Server=192.168.1.193\\SQLEXPRESS,59116;Initial Catalog=IdentityAdministrativeDashboard;User ID=globe;Password=globe;;Persist Security Info=False"
   ASPNETCORE_UserSettingsOptions__CreateAdmin: "True"
   ASPNETCORE_UserSettingsOptions__UserName: admin
   ASPNETCORE_UserSettingsOptions__UserPassword: admin
  volumes:
   - /https:/https:rw

 globe-identity-database:
  image: "mcr.microsoft.com/mssql/server"
  ports:
   - "1433:1433"
  environment:
   SA_PASSWORD: MyPassword001
   ACCEPT_EULA: Y
   MSSQL_PID: Express
  volumes:
   - /data:/data:rw
