//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Globe")]
[assembly: System.Reflection.AssemblyCopyright("Copyright ©2020 by Globe")]
[assembly: System.Reflection.AssemblyTrademark("")]

[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

