//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyTitleAttribute("Globe.Identity.Server.MultiTenant")]
[assembly: System.Reflection.AssemblyDescription("")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyProductAttribute("Globe.Identity.Server.MultiTenant")]
[assembly: System.Reflection.AssemblyCulture("")]

// Generated by the MSBuild WriteCodeFragment class.

