//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: AssemblyTitle("Globe.Identity.AdministrativeDashboard.Server")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyProduct("Globe.Identity.AdministrativeDashboard.Server")]
[assembly: AssemblyCulture("")]

// Generated by the MSBuild WriteCodeFragment class.

